### PR TITLE
Add GitHub Actions to build Docker images

### PR DESCRIPTION
**Pull request by pugnascotia**
Add a GitHub action for each Docker image in the repository. Each action builds a Docker image in order to check that it builds cleanly.

### CODE REVIEW

**Comment by pugnascotia** [comment]
Kibana kindly volunteered a break to demonstrate the actions working 😅

**Review by mgreau — APPROVED** [review]
LGTM

**Comment by mgreau** [comment]
```
 ---> Running in 93beeb3c2124
tar (child): /tmp/kibana.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
```

@pugnascotia Kibana build failed because of an issue already reported and fixed with https://github.com/elastic/kibana/pull/120991/files
I made a suggestion to do this update in https://github.com/elastic/dockerfiles/pull/90 
It means we will need to merge this PR with the Kibana failure if we want the GitHub action check to pass before merging #90.

**Comment by mgreau** [comment]
Thanks @pugnascotia, merging it to have these checks for #90

**Pull request merged**
